name: Publish to npm

on:
  push:
    branches:
      - main  # Trigger sul branch main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Permesso per commit e tag
      packages: write  # Permesso per pubblicare su npm

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Configure Git user (BEFORE running npm run release)
      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Step 5: Clean dist directory and build the project
      - name: Clean dist and build project
        run: |
          rm -rf dist
          npm run build

      # Step 6: Bump version and create changelog
      - name: Bump version and create changelog
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Push changes and tags to GitHub
      - name: Push changes and tags to GitHub
        run: |
          git push --follow-tags origin main

      # Step 8: Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}